### ISSUE TITLE
neural network visualization

### ISSUE THREAD

**Issue by RengarWang** [monokim/framework_tutorial#1]
hi, you did a good job in the experiment. It is suggested to set fitness to have procedures to jump out of the loop. For example, after running several laps without collision, the program will be terminated, and the neural network visualization at this time will be directly output, and the neural network at this time will be saved. Therefore, we can clearly see its node connection and each weight. thank you.

**Comment by monokim** [comment]
Okay, that is a good idea.
I will try some
