### ISSUE TITLE
Broken example

### ISSUE THREAD

**Issue by rubens21** [monokim/framework_tutorial#4]
Hi there,
The example looks to be broken.
I am newbie in Python, so I may be doing something wrong.

```
 File "[...]/framework_tutorial/gym_game/envs/pygame_2d.py", line 154, in action
    self.car.radars.clear()
AttributeError: 'list' object has no attribute 'clear'
```

Thank you for you awesome video! I wish all videos on Youtube were so straight into the topic as is yours.

**Comment by monokim** [comment]
list.clear() was added in python 3.3.  
Check your python version it is higher than 3.3.

**Comment by rubens21** [comment]
Worked :-) 
Thank you
